development:
  adapter: postgresql
  encoding: unicode
  host: 159.65.203.59
  port: 5432
  database: telegram_bot_test_dev
  pool: 2
  # username: aburyka
  # password: your_password

production:
  adapter: postgresql
  encoding: unicode
  host: 159.65.203.59
  port: 5432
  database: telegram_bot_test_prod
  pool: 2
  # username: your_username
  # password: your_password
